import tweepy
import time

#giant list of Navy OCS Appendix B information from https://www.public.navy.mil/netc/nstc/otcn/pdfs/OTCNINST%201530.6J%20CH-1%20-%20Officer%20Candidate%20Regulations%20(OCR).pdf

appendixb = [
"The Oath of Office \nI, (name), having been appointed an Ensign in the United States Navy, do hereby accept such appointment and do solemnly swear that I will Support and Defend the Constitution of the United States against all enemies, foreign and domestic, that I will bear",
"The Oath of Office (contd) \ntrue faith and allegiance to the same; that I take this obligation freely, without any mental reservation or purpose of evasion, and that I will well and faithfully discharge the duties of the office on which I am about to enter. So help me God.",
"The Pledge of Allegiance\nI pledge allegiance to the flag of the United States of America, and to the Republic for which it stands, one nation, under God, indivisible, with liberty and justice for all.",
"The Sailor's Creed (para 1)\nI am a United States Sailor. I will support and defend the Constitution of the United States of America and I will obey the orders of those appointed over me.",
"The Sailor's Creed (para 2)\nI represent the fighting spirit of the Navy and those who have gone before me to defend freedom and democracy around the world.",
"The Sailor's Creed (para 3)\nI proudly serve my country's Navy combat team with honor, courage and commitment. I am committed to excellence and the fair treatment of all.",
"Star Spangled Banner (para 1):\nO say can you see, by the dawn's early light,\nWhat so proudly we hail'd at the twilight's last gleaming,\nWhose broad stripes and bright stars through the perilous fight,\nO'er the ramparts we watch'd, were so gallantly streaming?",
"Star Spangled Banner (para 2):\nAnd the rocket's red glare, the bomb bursting in air,\nGave proof through the night that our flag was still there,\nO say does that star spangled banner yet wave\nO'er the land of the free and the home of the brave?",
"Anchors Aweigh (verse 1):\nStand Navy out to sea,\nFight our Battle Cry;\nWe'll never change our course,\nSo vicious foes steer shy-y-y-y.\nRoll out the TNT,\nAnchors Aweigh.\nSail on to Victory\nAnd sink their bones to Davy Jones, Hooray!",
"Anchors Aweigh (verse 2):\nAnchors Aweigh, my boys,\nAnchors Aweigh.\nFarewell to foreign shores,\nWe sail at break of day-ay-ay-ay.\nThrough our last night ashore,\nDrink to the foam,\nUntil we meet once more.\nHere's wishing you a happy voyage home.",
"Anchors Aweigh (verse 3):\nBlue of the Mighty Deep:\nGold of God's great sun.\nLet these our colors be\nTill all of time be done, done, done, done.\nOn seven seas we learn\nNavy's stern call:\nFaith, courage, service true,\nWith honor, over honor, over all.",
"The Marines' Hymn (verse 1):\nFrom the Halls of Montezuma\nTo the shores of Tripoli;\nWe fight our country's battles\nIn the air, on land, and sea;\nFirst to fight for right and freedom\nAnd to keep our honor clean;\nWe are proud to claim the title\nOf United States Marine.",
"The Marines Hymn(verse 2)\nOur flag's unfurled to every breeze\nFrom dawn to setting sun\nWe have fought in every clime and place\nWhere we could take a gun\nIn the snow of far-off Northern lands\nAnd in sunny tropic scenes\nYou will find us always on the job\nThe United States Marines",
"The Marines' Hymn (verse 3):\nHere's health to you and to our Corps\nWhich we are proud to serve;\nIn many a strife we've fought for life\nAnd never lost our nerve.\nIf the Army and the Navy\nEver look on Heaven's scenes,\nThey will find the streets are guarded\nBy United States Marines",
"CODE OF CONDUCT 1. I am an American, fighting in the forces which guard my country and our way of life. I am prepared to give my life in their defense.",
"CODE OF CONDUCT 2. I will never surrender of my own free will. If in command, I will never surrender the members of my command while they still have the means to resist.",
"CODE OF CONDUCT 3. If I am captured I will continue to resist by all means available. I will make every effort to escape and aid others to escape. I will accept neither parole nor special favors from the enemy.",
"CODE OF CONDUCT 4. If I become a prisoner of war, I will keep faith with my fellow prisoners. I will give no information or take part in any action which might be harmful to my comrades.",
"CODE OF CONDUCT 4 contd. If I am senior, I will take command. If not, I will obey the lawful orders of those appointed over me and will back them up in every way.",
"CODE OF CONDUCT 5. When questioned, should I become a prisoner of war, I am required to give name, rank, service number and date of birth. I will evade answering further questions to the utmost of my ability.",
"CODE OF CONDUCT 5 contd. I will make no oral or written statements disloyal to my country and its allies or harmful to their cause.",
"CODE OF CONDUCT 6. I will never forget that I am an American, fighting for freedom, responsible for my actions, and dedicated to the principles which made my country free. I will trust in my God and in the United States of America.",
"GENERAL ORDERS OF A SENTRY 1. Take charge of this post and all government property in view.",
"GENERAL ORDERS OF A SENTRY 2. Walk my post in a military manner, keeping always on the alert and observing everything that takes place within sight or hearing.",
"GENERAL ORDERS OF A SENTRY 3. Report all violations of orders I am instructed to enforce.",
"GENERAL ORDERS OF A SENTRY 4. Repeat all calls from any post more distant from the guard house than my own.",
"GENERAL ORDERS OF A SENTRY 5. Quit my post only when properly relieved.",
"GENERAL ORDERS OF A SENTRY 6. Receive, obey, and pass on to the sentry who relieves me all orders from the commanding officer, command duty officer, officer of the deck, and officers and petty officers of the watch only.",
"GENERAL ORDERS OF A SENTRY 7. Talk to no one except in the line of duty.",
"GENERAL ORDERS OF A SENTRY 8. Give the alarm in case of fire or disorder.",
"GENERAL ORDERS OF A SENTRY 9. Call the OOD in any case not covered by instructions.",
"GENERAL ORDERS OF A SENTRY 10. Salute all officers and all colors and standards not cased.",
"GENERAL ORDERS OF A SENTRY 11. Be especially watchful at night, and during the time for challenging, challenge all persons on or near my post, and allow no one to pass without proper authority.",
"Chief Warrant Officer Two (CWO2) Gold Bar with three blue breaks. One gold 1/2-inch stripe with three blue breaks outboard a specialty insignia. One gold 1/2-inch stripe with three blue breaks below a specialty insignia.",
"Chief Warrant Officer Three (CWO3) Silver Bar with two blue breaks. One gold 1/2-inch stripe with two blue breaks outboard a specialty insignia. One gold 1/2-inch stripe with two blue breaks below a specialty insignia.",
"Chief Warrant Officer Four (CWO4) Silver Bar with three blue breaks. One gold 1/2-inch stripe with one blue break outboard a specialty insignia. One gold 1/2-inch stripe with one blue break below a specialty insignia.",
"Chief Warrant Officer Five (CWO5) Silver Bar with one 1/8th inch horizontal blue line. Two thin gold stripes with one blue break outboard a specialty insignia. Two thin gold stripes with one blue break below a specialty insignia.",
"O-1 Ensign (ENS) One gold bar. One gold 1/2-inch stripe outboard a gold five pointed star. One gold 1/2-inch stripe below a gold five pointed star.",
"O-2 Lieutenant Junior Grade (LTJG) One silver barOne gold 1/2-inch stripe outboard one 1/4-inch goldstripe outboard a gold five pointed star. One gold 1/2-inch stripe below one 1/4- inch stripe below a gold five pointed star.",
"O-3 Lieutenant (LT)Two silver bars. Two gold 1/2-inch stripesoutboard a gold five pointedstar. Two gold 1/2-inch stripes below a gold five pointed star.",
"O-4 Lieutenant Commander(LCDR) Gold oak leaf. One gold 1/2-inch stripe outboard one gold 1/4-inch stripe outboard one gold 1/2- inch stripe outboard a gold five pointed star. One gold 1/2-inch stripe below one gold 1/4-inch stripe below one gold 1/2-inch stripe below a gold star.",
"O-5 Commander (CDR) Silver oak leaf. Three gold 1/2-inch stripes outboard a gold five pointed star. Three gold 1/2-inch stripes below a gold five pointed star.",
"O-6 Captain (CAPT) Silver eagle. Four gold 1/2-inch stripes outboard a gold five pointed star. Four gold 1/2-inch stripes below a gold five pointed star.",
"O-7 Rear Admiral Lower Half (RDML) One silver five pointed star. Gold shoulder boards with one silver five pointed star outboard a silver fouled anchor. One gold 2-inch stripe below a gold five pointed star.",
"O-8 Rear Admiral (RADM) Two silver five pointed stars. Gold shoulder boards with two silver five pointed stars outboard a silver fouled anchor. One gold 2-inch stripe below one gold 1/2-inch stripe below a gold five pointed star.",
"O-9 Vice admiral (VADM) Three silver five pointed stars. Gold shoulder boards with three silver five pointed stars outboard a silver fouled anchor. One gold 2-inch stripe below two gold 1/2-inch stripes below a gold five pointed star.",
"O-10 Admiral (ADM) Four silver five pointed stars. Gold shoulder boards with four silver five pointed stars outboard a silver fouled anchor. One gold 2-inch stripe below three gold 1/2-inch stripes below a gold five pointed star.",
"O-11 Fleet Admiral (FADM) Five silver five pointed stars. Gold shoulder boards with five silver five pointed stars outboard a silver fouled anchor. One gold 2-inch stripe below four gold 1/2-inch stripes below a gold five pointed star.",
"Marine (W1) Single bar device with a red background and one gold break.",
"Marine (CWO2) Single bar device with a red background and two gold breaks.",
"Marine (CWO3) Single bar device with a red background and one silver break.",
"Marine (CWO4) Single bar device with a red background and two silver breaks.",
"Marine (CWO5) Single silver bar device with a thin red break in the center.",
"Marine O-1 Second Lieutenant (2ndLt) One gold bar.",
"Marine O-2 First Lieutenant (1stLt) One silver bar.",
"Marine O-3 Captain (Capt) Two silver bars.",
"Marine O-4 Major (Maj) Gold oak leaf.",
"Marine O-5 Lieutenant Colonel (LtCol) Silver oak leaf.",
"Marine O-6 Colonel (Col) Silver eagle.",
"Marine O-7 Brigadier General (BGen) One silver five pointed star.",
"Marine O-8 Major General (MajGen) Two silver five pointed stars.",
"Marine O-9 Lieutenant General (LtGen) Three silver five pointed stars.",
"Marine O-10 General (Gen) Four silver five pointed stars.",
"E-1 Seaman Recruit (SR) None. None.",
"E-2 Seaman Apprentice (SA) Two diagonal bars. Two diagonal stripes.",
"E-3 Seaman (SN) Three diagonal bars. Three diagonal stripes.",
"E-4 Petty Officer Third Class (PO3) One eagle above one chevron. One eagle above one chevron.",
"E-5 Petty Officer Second Class (PO2) One eagle above two chevrons. One eagle above two chevrons.",
"E-6 Petty Officer First Class (PO1) One eagle over three chevrons. One eagle above three chevrons.",
"E-7 Chief Petty Officer (CPO) Gold fouled anchor with silver USN centered across the anchor. One eagle above one rocker above three chevrons.",
"E-8 Senior Chief Petty Officer (SCPO) Gold fouled anchor with silver USN centered across the anchor below one silver star. One silver star above one eagle above one rocker above three chevrons.",
"E-9 Master Chief Petty Officer (MCPO) Gold fouled anchor with silver USN centered across the anchor below two silver stars. Two silver stars above one eagle above one rocker above three chevrons.",
"E-9 Master Chief Petty Officer of the Navy (MCPON) Gold fouled anchor with silver USN centered across the anchor below three silver stars. Three gold stars above one eagle above one rocker above three chevrons with a gold star specialty mark.",
"Marine E-1 Private None.",
"Marine E-2 Private First Class (PFC) One stripe.",
"Marine E-3 Lance Corporal (LCpl) One stripe over crossed rifles.",
"Marine E-4 Corporal (Cpl) Two stripes over crossed rifles.",
"Marine E-5 Sergeant (Sgt) Three stripes over crossed rifles.",
"Marine E-6 Staff Sergeant (SSgt) Three stripes over crossed rifles over one rocker.",
"Marine E-7 Gunnery Sergeant (GySgt) Three stripes over crossed rifles over two rockers.",
"Marine E-8 Master Sergeant (MSgt) Three stripes over crossed rifles over three rockers.",
"Marine E-8 First Sergeant (1stSgt) Three stripes over one diamond over three rockers.",
"Marine E-9 Master Gunnery Sergeant (MGySgt) Three stripes over a bursting bomb over four rockers.",
"Marine E-9 Sergeant Major (SgtMaj) Three stripes over one star over four rockers.",
"Marine E-9 Sergeant Major of the Marine Corps (SMMC) Three stripes over the Marine Corps emblem centered between two five pointed stars over four rockers.",
"Naval Aviator Insignia: A gold embroidered or gold metal winged pin with a fouled anchor behind a shield in the center.",
"Naval Flight Officer Insignia: A gold embroidered or gold metal winged pin with a set of small, crossed, fouled anchors behind a shield in the center.",
"Surface Warfare Insignia: A gold embroidered or gold metal pin, with the bow and superstructure of a modern naval warship superimposed on two crossed swords, on a background of ocean swells.",
"Submarine Warfare Insignia: A gold embroidered or gold metal pin showing the bow view of a submarine proceeding on the surface with bow planes rigged for diving flanked by dolphins in horizontal position, their heads resting on the upper edge of the bow planes.",
"Special Warfare Insignia: A gold embroidered or gold metal pin with an eagle holding a trident and a handgun, in front of an anchor.",
"Naval Aviation Supply Insignia: A gold embroidered or gold metal winged pin with a supply corps oak leaf in the center.",
"Submarine Supply Insignia: A gold embroidered or gold metal pin with two dolphins facing a supply corps oak leaf in the center.",
"Surface Warfare Supply Insignia: A gold embroidered or gold metal pin with a supply corps oak leaf centered on the bow and superstructure of a modern naval warship superimposed on two crossed naval swords, on a background of ocean swells.",
"Diving Officer Insignia: A gold embroidered or gold metal pin with two upright sea horses facing a diving helmet, and two tridents projecting upward and canted outward from the diving helmet's cover. A double carrick bend superimposed on the breast plate.",
"Seabee Combat Warfare Specialist Insignia: A gold embroidered or gold metal pin with a bee on crossed sword and gun superimposed on an anchor on a background of leaves.",
"Special Operations Officer Insignia: A gold embroidered or gold metal pin, with the bow and superstructure of a modern naval warship on a background of ocean swells",
"Special Operations Officer Insignia: (contd) with an ordnance disposal bomb over crossed lightning rays on one side, and a diving helmet over two tridents on the other.",
"Information Dominance Insignia: A gold embroidered or gold metal pin of a globe superimposed on an anchor over a crossed sword and lightning bolt, on a background of ocean swells.",
"Professional Aviation Maintenance Officer: A gold embroidered or gold metal winged pin with a silver eagle perched on a shield in the center, over a gold AERO MAINTENANCE streamer.",
"Explosive Ordinance Disposal Officer: A gold embroidered or gold metal pin featuring: A wreath to commemorate EOD personnel who have been killed in the line of duty. A bomb, which represents EOD personnel’s goal of making sure bombs do not go off.",
"Explosive Ordinance Disposal Officer: (contd) Lightning bolts, which symbolize bombs’ potential destructive power and EOD personnel’s efforts to defeat explosive devices. A shield, representing the EOD mission of protecting people and property from accidental explosions.",
"Fleet Marine Force Officer Insignia: A gold embroidered or gold, highly polished, metal device depicting the eagle, globe and anchor atop two crossed rifles on a background of ocean swells breaking on a sandy beach.",
"Fleet Marine Force Officer Insignia: (contd) The eagle continents and Rifles shall be highlighted with a highly polished silver finish.",
"MISSION OF THE NAVY\nThe mission of the Navy is to maintain, train, and equip combat-ready naval forces capable of winning wars, deterring aggression, and maintaining freedom of the seas.",
"Levels of War\nStrategic level focuses on supporting national goals.\nOperational level concerns forces collectively in theater.\nTactical level involves the details of individual engagements.",
"War at Sea\nWar at sea is the application of decisive offensive force to achieve control of the sea which is the first step in establishing our superiority in any region.",
"Littoral Warfare\nLittoral warfare is warfare in that portion of the world's land masses, adjacent to the oceans within direct control of and vulnerable to the striking power of sea-based forces.",
"Strike Warfare (STW) (Primary Warfare Area) – Any combination of naval forces that intends to inflict damage on or destroy the target objective.",
"Amphibious Warfare (Primary Warfare Area) – Establishing a landing force on a hostile shore.",
"Mine Warfare (MIW) (Primary Warfare Area) – The use of mines and mine countermeasures to control or deny the use of sea or harbor areas through the laying of minefields and countering enemy mine warfare through the destruction or neutralization of hostile minefields.",
"Air Warfare (AW) (Primary Warfare Area) – Those actions required to destroy or reduce the enemy air and missile threat to an acceptable level.",
"Undersea Warfare (USW) (Primary Warfare Area) – Those actions taken to deny the enemy effective use of his submarines and the undersea environment.",
"Surface Warfare (SUW) (Primary Warfare Area) – Deny the enemy effective use of his surface warships and merchant capability.",
"Special Warfare (Supporting Warfare Area) – Non-conventional operations in the coastal, riverine, and maritime environments. Naval special warfare emphasizes small, flexible, mobile units operating under, on, and from the sea.",
"Intelligence (Supporting Warfare Area) – Assessment and management of information obtained via surveillance, reconnaissance and other means to produce timely information of potential enemies and threats.",
"Electronic Warfare (EW) (Supporting Warfare Area) – Ensure the effective use of the electromagnetic spectrum to friendly forces while denying its use to the enemy.",
"Logistics (Supporting Warfare Area) - Re-supply of combat consumables to combat forces within a theater of operations.",
"LEADERSHIP TRAIT 1. Judgment: The ability to weigh facts and possible solutions on which to base sound decisions.",
"LEADERSHIP TRAIT 2. Justice: Giving reward and punishment according to merits of the case in question; the ability to administer a system of rewards and punishments impartially and consistently.",
"LEADERSHIP TRAIT 3. Decisiveness: Ability to make decisions promptly and to announce them in clear, forceful manner.",
"LEADERSHIP TRAIT 4. Initiative: Taking action in the absence of orders.",
"LEADERSHIP TRAIT 5. Dependability: The certainty of proper performance of duty.",
"LEADERSHIP TRAIT 6. Tact: The ability to deal with others without creating offense.",
"LEADERSHIP TRAIT 7. Integrity: Uprightness of character and soundness of moral principles; includes the qualities of truthfulness and honesty.",
"LEADERSHIP TRAIT 8. Endurance: The mental and physical stamina measured by the ability to withstand pain, fatigue, stress and hardship.",
"LEADERSHIP TRAIT 9. Bearing: Creating a favorable impression in carriage, appearance and personal conduct at all times.",
"LEADERSHIP TRAIT 10. Unselfishness: Avoidance of providing for one's own comfort and personal advancement at the expense of others.",
"LEADERSHIP TRAIT 11. Courage: The mental quality that recognizes fear of danger or criticism, but enables a person to proceed in the face of it with calmness and firmness.",
"LEADERSHIP TRAIT 12. Knowledge: Understanding of a science or an art. The range of one's information, including professional knowledge and an understanding of your Sailors.",
"LEADERSHIP TRAIT 13. Loyalty: The quality of faithfulness to country, the Navy, the unit, to one's seniors, subordinates and peers.",
"LEADERSHIP TRAIT 14. Enthusiasm: The display of sincere interest and exuberance in the performance of duty.",
"LEADERSHIP TRAIT 15. Honor: To regard or treat with honor, esteem, or respect; to revere; to treat with deference and submission."]

# Authenticate to Twitter
auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
auth.set_access_token(access_token, access_token_secret)

# Create API object
api = tweepy.API(auth)

while True:
  for x in appendixb:
    print(x)
    time.sleep(3600) # post the next memorization item to twitter every hour. Deployment from an Amazon EC2 instance. 
    
    # twitter bot is at https://twitter.com/OCS_Appendix_B
